### PR TITLE
NYT Articles Page Clone - Milestones 1-6

### PR DESCRIPTION
**Pull request by SamArsanios**
In this project we:
-Added Setup for the linters that are going to be used in the project.
-Added the HTML Markup for the web page for the article page section.
-Added the CSS style for fonts, colors, and positioning for the article page.

### CODE REVIEW

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @SamArsanios and @AshakaE, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏  I appreciate your hard work in replicating nytimes.com. Kindly fix the following issues.

[REQUIRED]

- [x] Fix the readme file to add more content.
- [x] Fix the bottom part of the page.
- [x] Fix the linting errors.
- [x] Add links to more popular articles on the bottom rightmost side.
- [x] The header should have a fixed position (it should stick to the top part of the screen)
- [x] Fix the main article font.
- [x] The main article image cation should start in a new line.
- [x] Kindly use a CSS grid in the project.
- [x] Add the Editor's picks section on the rightmost side. (It uses <aside> tag)
aside article
- [x] Fix the bottom part of the page, compare your clone with the original page.
original bottom
bottom parts


[OPTIONAL] 

- [ ] Add a fixed footer (it sticks to the bottom part of the screen)
sticky footer

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey team, 👋

You have done an amazing job implementing the project requirements of this project.

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 

- [x] You have linter errors. Always make sure you dont have any linter errors before submitting for review.

- [x] Make sure you don't get a horizontal scroll. Ensure that everything fits within the width of the browser as it is on the real page.

- [x] The section titled **Most Popular** is overlapping. see image below
screenshot-ashakae github io-2020 11 26-20_36_34

- [x] The footer section is not properly aligned in the center. Please fix this

- [x] On the section titled **Theory of Inflation**, the images are not properly aligned with their text. please fix this. see image below
screenshot-ashakae github io-2020 11 26-20_38_49

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime**
I would be happy to help! 👩‍💻 

Happy coding 🤓

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey team,

Please make the changes requested in the previous review and submit another review.

If you're having trouble implementing any of the suggested changes, please reach out to me on slack as **Phillip Musiime**

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.##
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @AshakaE and @SamArsanios ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**[OPTIONAL]** Add a fixed footer 
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
